### ISSUE TITLE
Tippy tema mangler

### ISSUE THREAD

**Issue by ncjelu** [detfaellesdesignsystem/dkfds-plugins#7]
Hej, 

Vi bruger DKFDS 5.0.0 og vil gerne lave et tooltip. Ifølge dokumentationen burde Tippy-temaet ligge i dette projekt, men det ligger ikke på den dokumenterede sti: [path-to-plugins-project]/dist/css/dkfds-tippy-theme.standalone.min.css 
(https://designsystem.dk/udvidelser/tippy)

**Comment by detfaellesdesignsystem** [comment]
Hej @ncjelu,

Tak for din henvendelse - og godt fanget.

Jeg er ved at lave en ny release lige nu. Så der burde være en ny version klar til dig om en halv times tid.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by ncjelu** [comment]
Tak!
